<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateGenerateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'discount_app' => 'required',
            'expired_range' => 'required|integer',
            'app_url' => 'required|string',

        ];
    }

    public function validationData()
    {
        return parent::validationData(); // TODO: Change the autogenerated stub
    }
}
